services:
  - type: web
    name: free-musicflow
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JAMENDO_CLIENT_ID
        sync: false
